### ISSUE TITLE
B.4. Master Folio/Desk Folio

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#13]
## Basic Flow
1. Klik new pada halaman Folio
2. Pilih tipe Master Folio/Desk Folio
3. Pilih group dan customer
4. Klik tombol save

## Alternate Flow
2.1. Tipe yang dipilih Guest Folio, maka sistem memberikan warning bahwa Guest Folio tidak bisa dibuat manual
4.1. Isian lengkap, maka akan membuat record pada tabel Folio

| Attribute | Type | Value |
| - | - | - |
| open | Datetime | form.open |
| close | Date | form.close |
| type | Select(Guest, Master, Desk) | form.type |
| group_name | Link(Group) | form.group |
| status | Select(Open,Close,Cancel) | Open |
| customer_id | Link (Customer) | form.customer |
| bill_instruction | Small Text | form.bill_instruction |
| total_debit | Currency | 0 |
| total_credit | Currency | 0 |
| balance | Currency | 0 |

## Post Condition
1. Master Folio/Desk Folio Created

**Comment by anra54** [comment]
option Guest disembunyikan jika folio dibuat manual. jika bukan lewat new form, opsi Guest muncul kembali

**Comment by sumayyah42** [comment]
Update tambah field isian Open dan Close Folio

**Comment by sumayyah42** [comment]
> option Guest disembunyikan jika folio dibuat manual. jika bukan lewat new form, opsi Guest muncul kembali

saat ini option Guest ketika membuat Folio manual muncul kembali

**Comment by anra54** [comment]
> > option Guest disembunyikan jika folio dibuat manual. jika bukan lewat new form, opsi Guest muncul kembali
> 
> saat ini option Guest ketika membuat Folio manual muncul kembali

fixed at 393bfe3873db495fe719ac05de77adc5f55ef7c0
