### ISSUE TITLE
B.6. Refund

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#19]
## Contoh Layout
![image](https://user-images.githubusercontent.com/25950059/76744351-ac3afb00-67a6-11ea-9f9b-c2db9554f3ef.png)

![image](https://user-images.githubusercontent.com/25950059/76745482-8151a680-67a8-11ea-84e5-1d222cd5cafd.png)

## Precondition
1. Status Folio Open

## Basic Flow
1. Klik tombol Refund
2. Ketika balance negatif, sistem akan menampilkan nominal amount default (tapi masih bisa diedit). Contoh balance -120.000, maka ketika klik refund, field amount akan otomatis terisi 120.000
3. Isi field remark jika ada
4. Klik Save

## Alternate Flow
2.1. balance Folio 0 atau postif, maka field amount kosong
4.1. Isian lengkap, maka akan membuat record Folio Transaction sebagai berikut

| Field | Doctype Type | Value | 
| - | - | - | 
| audit_date | date | audit_history.audit_date | 
| charge_name | Link | transaction_type.name | 
| type | Select(Credit, Debit) | transaction_name.type | 
| debit_account | Link | inn_hotel_settings.refund_debit_account | 
| credit_account | Link | inn_hotel_settings.refund_credit_account |
| amount | Currency | form.amount | 
| sub_folio | Select(A,B,C,D) | form.sub_folio |
| remark | Data | form.remark |
| posting | Select(No, Yes) | No | 
| is_void | Select(No, Yes) | No | 
| shift_id | Link | getOpenShiftId() |

## Post Condition
1. Folio Transaction Refund akan bertambah

**Comment by anra54** [comment]
@sumayyah42 

> balance -120.000, maka ketika klik refund, field amount akan otomatis terisi 120.000

-120.000 itu payment > charge atau payment < charge?

> 
> Notes: 
> - field is_refund perlu ditambahkan di doctype Folio Transaction. Atribut ini digunakan untuk pengecekan refund pada Cashier Report
> - credit_account dan debit_account refund diambil dari Inn Hotel Settings. Tambahkan fields refund_credit_account dan refund_debit_account bertipe Link ke doctype Account.

Kenapa perlu field baru? kenapa tidak menggunakan doctype `inn_folio_transaction_type`?

**Comment by sumayyah42** [comment]
> -120.000 itu payment > charge atau payment < charge?

payment > charge (totl credit folio > total debit folio)

> Kenapa perlu field baru? kenapa tidak menggunakan doctype `inn_folio_transaction_type`?

Kepikiran bukan dari `inn_folio_transaction_type` karena ga ada yg menandakan perbedaan tansaction type refund dan transaction type lainnya selain dari nama. Kalo bisa berbeda hanya dari nama, harus ada penjelasan standar penamaan dari transaction type refund.

**Comment by anra54** [comment]
> Kepikiran bukan dari `inn_folio_transaction_type` karena ga ada yg menandakan perbedaan tansaction type refund dan transaction type lainnya selain dari nama. Kalo bisa berbeda hanya dari nama, harus ada penjelasan standar penamaan dari transaction type refund.

Dari nama aja kan udah jadi pembeda yang valid toh? Unique namenya doctype.
Dan kalau debit dan credit accountnya ngambil dari Inn Hotels Setting bukannya itu juga menandakan perbedaannya? 
Sepertinya alasan dibikin doctype inn_folio_transaction_type memang untuk handle variasi dari tipe2 transaksi di folio bukan? 
 Juga, kalau semisalnya bukan dari inn_folio_transaction_type, jadi diisi apa transaction type nya untuk folio transaction tipe refund? pilihannya sekarang Room Payment, Deposit, DP Kamar, Additional Charge, Cancellation Fee, Late Checkout sama Early Checkin?

Mungkin coba dijelaskan dengan contoh kasus di mana kasus dua transaksi yang tidak ada menandakan perbedaan dari refund dan bukan refund.

**Comment by sumayyah42** [comment]
oke, berarti untuk refund cukup dari `inn_folio_transaction_type`. Selanjutnya deskripsi akan diedit dan akan ada penambahan pada  [tabel ini](https://github.com/purwaren/front-desk/issues/9#issuecomment-596359965)
