### ISSUE TITLE
B.8. Hide and Show Void Transaction

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#30]
Untuk Setiap Void Transaction di dalam Folio, tampilan defaultnya ada disembunyikan dari tabel Folio Transaction. Untuk memunculkannya, klik check box Show Void Transaction.
Contoh Layout
![image](https://user-images.githubusercontent.com/25950059/77871172-79483b00-726d-11ea-8cf7-90d8a693aa49.png)

**Comment by anra54** [comment]
checkbox diganti menjadi button agar flag not saved form tidak berubah ketika mengubah visibility voided transactions
