### ISSUE TITLE
F.1. Clean Room

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#32]
## Precondition
1. Terdapat record di doctype Inn Room 
2. Role user adalah Housekeeping/Housekeeping Supervisor/Housekeeping Assistant

## Basic Flow
1. Buka menu Inn Room
2. Pilih/klik Room yang akan di bersihkan
3. Klik tombol menu di pojok kanan atas
4. Klik tombol Clean Room 
(Note: posisi tombol update status berbeda dari sebelumnya, bukan ada di tombol  ![image](https://user-images.githubusercontent.com/25950059/77871956-d47b2d00-726f-11ea-9b70-3ec4cbe16002.png) tapi berada di ![image](https://user-images.githubusercontent.com/25950059/77872482-3ee09d00-7271-11ea-8c49-83ab98a36cb9.png) di halaman Room yg dipilih karena untuk memudahkan pengguna mobile. Pada tampilan mobile, tidak ada kotak check box di halaman List)
![image](https://user-images.githubusercontent.com/25950059/77872665-d3e39600-7271-11ea-8d0e-c13444d55e6a.png)

## Alternate Flow
4.1. Current Door Status No Status atau Sleeping Out
4.2. Current Door Status Do Not Disturb atau Double Lock

## Alternate Subflow
4.1.1. Current Room Status  Vacant Dirty, setelah Clean Room  menjadi Vacant Clean
4.1.2. Current Room Status Occupied Dirty, setelah Clean Room menjadi Occupied Clean
4.1.3. Current Room Status Vacant Clean, setelah Clean Room menjadi Vacant Ready jika role nya adalah Housekeeping Supervisor/Housekeeping Assistant
4.1.4. Current Status  Room Vacant Clean, setelah Clean Room tidak terjadi perubahan jika role nya adalah Housekeeping
4.1.5. Current Room Status Occupied Clean, setelah Clean Room status tidak berubah
4.1.6. Current Room Status Vacant Ready, tidak terjadi perubahan status setelah Clean Room

4.2.1. Tidak terjadi perubahan status 

## Post Condition
1. Status room mengikuti kondisi pada alternate subflow

**Comment by sumayyah42** [comment]
Tombol clean di sebelah mana ya? di tab menu tidak ada 
![image](https://user-images.githubusercontent.com/25950059/79098402-12a63f80-7d8c-11ea-8ab2-058f7ee8ea29.png)

**Comment by anra54** [comment]
buttons added di page room. dikira dari screenshot file yang di issue, tombolnya ada di halaman list of room.

**Comment by sumayyah42** [comment]
> 4.1.3. Current Room Status Vacant Clean, setelah Clean Room menjadi Vacant Ready jika role nya adalah Housekeeping Supervisor/Housekeeping Assistant
> 4.1.4. Current Status Room Vacant Clean, setelah Clean Room tidak terjadi perubahan jika role nya adalah Housekeeping

Saat ini untuk role Housekeeping masih bisa mengupdate status room menjadi Vacant Ready melalui Clean Room. Buat menjadi hanya yang role nya Housekeeping Supervisor atau Housekeeping Assistant yang bisa update dari Vacant Clean ke Vacant Ready
