### ISSUE TITLE
B.9. Add Package

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#40]
## Doctype Package
| field | Type | Required | Detail
-|-|-|-
name | Data | Yes |
active | Check |  |
amount_per_pax | Currency | Yes |
Tax and Service | Link (Inn Tax List} | Yes |
total_pax | Int | yes | |
total_amount | Currency| | Calculated automatically
total_amount_after_tax | Currency | | Calculated automatically
debit_account | Link (Account) | Yes |
credit_account | Link (Account) | Yes |
package_detail | Table | | | 

Table package_detail
| field | Type | Required | Detail
-|-|-|-
name | Link (Package Detail Name) | no |
quantity | Int | no | 
amount | Currency | no | hanya sebagai detail, tidak berkaitan dengan harga total

atribut dari Package Detail Name cukup nama saja

## Precondition
1, Folio berstatus Open

## Basic Flow
1. Pilih Folio berstatus Open
2. Klik tombol Add Package
3. Sistem menampilkan Package yang aktif (active=true)
4. Pilih salah satu Package
5. Pilih Sub Folio
6. Isi remark jika ada
7. Klik tombol Save

## Alternate Flow
7.1. Isian field required (Package dan subfolio) sudah diisi, maka akan menyimpan record pada doctype Folio Transaction
| Field | Doctype Type | Value
| - | - | -
| audit_date | date | getAuditDate()
| charge_name | Link | package.name
| type | Select(Credit, Debit) | Debit
| debit_account | Link | package.debit_account 
| credit_account | Link | package.credit_account
| amount | Currency | package.total_amount_after_tax
| sub_folio | Select(A,B,C,D) | form.subfolio
| remark | Data | form. remark
| posting | Select(No, Yes) | No
| is_void | Select(No, Yes) | No
| shift_id | Link | getOpenShiftId()

## Post Condition
1. Folio Transaction dengan nama Package bertamah

**Comment by anra54** [comment]
@sumayyah42 charge name di folio transaction kelinknya ke Inn Folio Transaction Type [(referensi)](https://github.com/purwaren/front-desk/issues/9#issuecomment-596359965), jadi ga bisa Link ke package.name. Harus buat transaction type baru yang terkait dengan package
