### ISSUE TITLE
[Bug] Infinite Loop While Check In

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#49]
Ketika Start Check In Process, terjadi infinite loop dari range code baris [ini](https://github.com/purwaren/front-desk/blob/92d674d002d35eacf1e87f15e6733c5f2fda61dc/inn/inn_hotels/doctype/inn_reservation/inn_reservation.js#L85) hingga ke [blok if ini](https://github.com/purwaren/front-desk/blob/92d674d002d35eacf1e87f15e6733c5f2fda61dc/inn/inn_hotels/doctype/inn_reservation/inn_reservation.js#L93)

Infinite loop ini membuat set actual room rate menjadi tidak bisa diisi.
Jika diperlukan, set actual room rate bisa ditampilkan sejak awal reservation (bukan saat check in process berlangsung)

**Comment by anra54** [comment]
coba fix yg dipush di f9b219ea2d373a1b3cb8a92e1fcf5e4c179a97b3
