### ISSUE TITLE
[Improvement] Add Actual Rate Before Check In

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#59]

**Comment by anra54** [comment]
@summayah:

fix committed at 19dc282ca6019f8e5fb1fe670a6a210e771e2dd8. Metode menggunakan placeholder variable `init_actual_room_rate` yang set_only_once. 

Sebelum checkin process:
- `init_actual_room_rate` not hidden
- `actual_room_rate` hidden
Saat checkin process dimulai:
- isi dari `init_actual_room_rate` akan disalin ke `actual_room_rate`
- `init_actual_room_rate` hidden
- `actual_room_rate` not hidden

**Comment by sumayyah42** [comment]
@anra54 setelah save reservation sebelum check in process, init_room_rate tidak muncul pada halaman
![image](https://user-images.githubusercontent.com/25950059/84756908-a0511600-afed-11ea-867a-6df480033ede.png)

**Comment by anra54** [comment]
fix at 7ef47cc5c79c8b6d6e9134ecc79eef8331d4054e
