### ISSUE TITLE
H.1. Print Material Request Custom

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#64]
Tambahkan print format Purcase Request pada doctype Material Request. Isi print seperti format print standard sebagai berikut
![image](https://user-images.githubusercontent.com/25950059/84889206-b1b82200-b0c2-11ea-81bb-2c9da9d1fc9e.png)

Dengan penambahan 2 komponen:
1. Tambah total harga pembelian pada bagian paling bawah list item yg dibelanjakan, dengan menjumlah seluruh amount

2. Kolom Tanda tangan di bagian paling bawah print dg layout seperti berikut
![image](https://user-images.githubusercontent.com/25950059/84889711-8124b800-b0c3-11ea-8f97-642d64ba9c8c.png)

**Comment by anra54** [comment]
@sumayyah42 
Karena doctype stock bagian dari ERPNext, bukan dari front_desk, jadi tidak bisa dipush seperti commit biasanya. Jadi saya kasih tutorial step by step cara membuat custom print format tanpa coding di sini aja ya, sebagai referensi.

## Tutorial
### I. Buat Print Format Baru
- Buka Satu Material Request, lalu klik tombol print sehingga muncul halaman Print Preview. Klik tombol Customize... Pastikan print format yang dipilih (dropdown paling kiri) adalah Standard.
![image](https://user-images.githubusercontent.com/4516687/84896483-3c524e80-b0ce-11ea-917a-24d274bd51c0.png)

- Isi New Print Format Name sesuai kebutuhan, pastikan Based On mengacu ke Standard, lalu klik start di kanan atas. Jika tidak, klik Close, lalu pilih print format dropdown di Halaman Print Preview menjadi Standard
![image](https://user-images.githubusercontent.com/4516687/84896756-ac60d480-b0ce-11ea-949d-90208cc46d47.png)

### II. Buat Sections Baru
- Di halaman Print Format Builder, scroll ke bawah, klik dua kali tulisan "+ Add a new section" untuk membuat 2 section baru. 
![image](https://user-images.githubusercontent.com/4516687/84897150-5e989c00-b0cf-11ea-986a-e901d4c8cc1c.png)

- Geser (dengan cara hold tombol hamburger di kiri atas section) dua section baru tsb ke atas, sehingga berada di bawah section berjudul "More Information"
![image](https://user-images.githubusercontent.com/4516687/84897071-3f9a0a00-b0cf-11ea-81e0-09358f3ddeba.png)

### III. Buat Section Separator
- Drag label "Custom HTML" di sidebar ke section baru paling atas, dan drop di dalamnya sehingga menjadi seperti berikut:
![image](https://user-images.githubusercontent.com/4516687/84897339-9b649300-b0cf-11ea-97f6-9a105725a92e.png)

- Lalu klik tombol "Edit HTML" pada section baru tersebut, paste code:
```
<br /><br /><br /><br /><br /><br /><br />
```
di window pop up yang muncul, lalu klik Update.
![image](https://user-images.githubusercontent.com/4516687/84897710-47a67980-b0d0-11ea-8000-dbeafbc4f13b.png)

### IV. Buat Section untuk Tanda Tangan
- Klik tombol roda gigi di section baru yang kedua, pilih 3 di dropdown "No of Columns", lalu klik Update.
![image](https://user-images.githubusercontent.com/4516687/84898088-e337ea00-b0d0-11ea-988d-97425bb86575.png)

- Drag label "Custom HTML" ke masing-masing kolom yang baru dibuat, masing-masing satu kali sehingga mejadi sebagai berikut:
![image](https://user-images.githubusercontent.com/4516687/84898287-3611a180-b0d1-11ea-836b-d1ea8b80a670.png)

- Klik Edit HTML pada kolom baru paling kiri, lalu masukkan code:
```
<p class="text-center">Requestor</p>
<br /><br /><br /><br /><hr><br />
```
dan klik tombol update.
Lakukan kepada dua kolom selanjutnya. Untuk kolom tengah masukkan code:
```
<p class="text-center">Purchasing</p>
<br /><br /><br /><br /><hr><br />
```
Untuk kolom paling kanan masukkan code:
```
<p class="text-center">Accounting Supervisor</p>
<br /><br /><br /><br /><hr><br />
```
Sehingga hasilnya mejadi seperti berikut:
![image](https://user-images.githubusercontent.com/4516687/84899744-4591ea00-b0d3-11ea-99b2-da5ba17434f7.png)

### V. Penyesuaian properties dari Print Format
- Scroll ke atas kembali di halaman Print Format Builder, lalu klik tombol "Edit Properties" di bawah tombol Save.
![image](https://user-images.githubusercontent.com/4516687/84900130-e1bbf100-b0d3-11ea-8dd8-b58e9d320a31.png)

- Di halaman properties, pilih Yes pada dropdown Standard, dan pastikan tiga ceklis options dari "STYLE SETTINGS" tidak tercentang. Klik Save pada bagian atas halaman untuk menyimpan.
![image](https://user-images.githubusercontent.com/4516687/84900437-5131e080-b0d4-11ea-8b47-d0f9f7a0f519.png)

**Comment by sumayyah42** [comment]
oke makasih mas. kalo untuk penghitungan total amount nya gimana ya mas? bisa digabung ke Items (Table) atau harus bikin section baru?

**Comment by anra54** [comment]
waduh ada total amountnya ya.. ketinggalan.. sebentar saya coba bikin. Mudah2an bisa.. xD

**Comment by anra54** [comment]
@sumayyah42 updated bu. Jadi section Separator-nya diganti jadi section Total Amount. Cukup ganti isi Custom HTMLnya aja

**Comment by sumayyah42** [comment]
siapp, dicoba
