### ISSUE TITLE
[Bug] Audit Date in Room Charge Posting

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#67]
Berikut data pada list dayend close
![image](https://user-images.githubusercontent.com/25950059/85003901-1043d580-b181-11ea-9653-614d878a4445.png)

ketika klik record yg sudah close, field audit date selalu mengecek latest audit date, padahal seharusnya menyimpan data audit data sesuai pelaksanaan dayend close
![image](https://user-images.githubusercontent.com/25950059/85003963-2487d280-b181-11ea-8aaf-28a6ec1072a3.png)
Keterngan: Audit date dari RCP di atas adalah tgl 17-06-2020, namun karena field audit_date selalu mengecek latest audit date, value yg terlihat menjadi latest audit date saat ini (18-06-2020)

**Comment by anra54** [comment]
fix pushed at commit cbc00321d184a12daaae227f5a2017f0e66ea406
