### ISSUE TITLE
[Improve] Jurnal Entry Folio berstatus Close

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#71]
Untuk setiap Folio berstatus Close dg close date = latest audit date, buat jurnal entry sebagai berikut
- Credit Account: semua Debit Account dari Folio Transaction berstatus Debit (charge)
- Debit Account: semua Credit Account dari Folio Transaction berstatus Credit (payment)

Jurnal diposting ketika Process Dayend Close

Contoh Folio Transaction
![image](https://user-images.githubusercontent.com/25950059/85109696-eef3ef80-b23b-11ea-9be8-db0d4947f8c9.png)

Berdasarkan Folio yg sudah Close tersebut, ketika Dayend Close terdapat jurnal entry berikut
Account | Party | Debit | Credit
-|-|-|-
2110.005 - A/P Guest Deposit - HDI | inn_folio.customer | Rp 388.000,00 | 
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 254.548,00 
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 25.454,00
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 28.000,00
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 66.115,00
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 6.611,00
1133.003 - A/R Guest Ledger - HDI | inn_folio.customer | | Rp 7.272,00

Dengan Remark: Closed Folio Transaction

**Comment by sumayyah42** [comment]
![image](https://user-images.githubusercontent.com/25950059/85153982-0dc8a500-b281-11ea-8794-cd1e37f94a17.png)
![image](https://user-images.githubusercontent.com/25950059/85153920-f984a800-b280-11ea-831a-2cda7003291d.png)
@anra54 penempatan credit debit nya terbalik. Akun A/R (Credit Account dari Folio Transaction dg flag Credit) seharusnya berada di Credit dan akun A/P ada di debit

**Comment by anra54** [comment]
@sumayyah42 fix at 5f61863044da4db1163fec4240c891a1f53e6b44
