### ISSUE TITLE
[Improve] Folio Transaction Type

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#72]
- Terdapat penambahan Folio Transaction Type dengan nama Payment, akun kredit ke 2110.005 - A/P Guest Deposit - HDI. Buat update yg dibutuhkan agar bisa tercatat pada tabel Payment di Inn Shift
- Terdapat update Folio Transaction Type dari nama DP Kamar menjadi Down Payment. Update nama tersebut di kodingan backend

**Comment by anra54** [comment]
[List of Inn Folio Transaction Type](https://github.com/purwaren/front-desk/issues/9#issuecomment-596359965) jg diupdate
Setelah issue ini dipull dan dinaikkan di server:
-  klik tombol Generate Folio Transaction Type untuk menambahkan transaction type baru yaitu Payment dan Down Payment.
- Ke Halaman Inn Folio Transaction Type, lalu uncheck Included in Dropdown? dari DP Kamar
