### ISSUE TITLE
[Improve] Bundle Transaction Type Trx id 

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#85]
Untuk setiap satu bundle transaction type, terdapat atribut id yang menandakan bahwa transaksi tersebut berasal dari satu transaksi yang sama. Contoh bundle
1. Room charge - Room charge tax/service - breakfast charge - breakfast charge tax/service
2. Package - Package tax
dll (mungkin akan bertambah, seperti laundry dan laundry charge, etc)

**Comment by sumayyah42** [comment]
@anra54 mau minta tolong dijelasin flow nya mas supaya room charge dan room charge tax/service bisa menjadi satu bundle

**Comment by anra54** [comment]
gak ada flownya sih @sumayyah42, folio yg satu bundle field `ftb_id`nya sama.. `ftb_id` mengacu ke doctype 'Inn Folio Transaction Bundle'
