### ISSUE TITLE
[Improve] Add Row Total

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/front-desk#87]
![image](https://user-images.githubusercontent.com/25950059/88268304-6d8cf280-ccfc-11ea-90e0-e629e13d3581.png)

Pada Bagian Already Posted di Inn Room Charge Posting, tambahkan baris total di paling bawah yang menghitung jumlah actual rate dari keseluruhan kamar

**Comment by anra54** [comment]
Well, karena sekarang Already Posted bakal direfer sama satu field lagi, ada kemungkinan inkonsistensi data dengan skenario:
1. user post room charge.
2. user void room charge folio transaction terkait di folio.

Solusi dari gw, ada tambahan langkah jika Void folio transaction room charge, akan juga menghapus row terkait di Table Already Posted. Bagaimana @sumayyah42?

**Comment by sumayyah42** [comment]
Iya boleh mas, biar konsisten. Berarti step itu bakal dijalanin kalo udah di approve ya void nya

**Comment by anra54** [comment]
Done di push commit b4090d6e9cb7d259f0590060d6b6fda2ee4ba7cf, tetapi dengan catatan:
Ketika ada aksi void Room Charge, yang mengakibatkan hilangnya transaction terkait dari table Already Posted, User **HARUS** masuk ke Room Charge Posting yg masih terbuka tsb, lalu **Refresh halaman** dan **Klik Tombol** `Populate/Refresh To Be Posted` sehingga Room Charge transaction muncul kembali di Table  To Be Posted.

Kalau tidak dilakukan, maka ada kemungkinan ada Room Charge yang tidak terposting.

Saran saya untuk Good Habit yg dienforce ketika sebelum close Room Charge Posting, adalah user klik tombol `Populate/Refresh To Be Posted` untuk memastikan tidak ada Room Charge Posting yg belum masuk.
